id: GCP - Firewall Remediation
version: -1
name: GCP - Firewall Remediation
description: Replace current firewall rules with limited access firewall rules.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: e783f34e-432b-4f40-8761-5958f39d0248
    type: start
    task:
      id: e783f34e-432b-4f40-8761-5958f39d0248
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: afd45690-ffd2-446e-8dcc-6e346e3ace58
    type: condition
    task:
      id: afd45690-ffd2-446e-8dcc-6e346e3ace58
      version: -1
      name: Is Google Cloud Compute enabled and are Input values defined?
      description: Determines if the AWS - EC2 integration instance is configured and Input values are defined to pull enrichment data.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "32"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: Google Cloud Compute
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
          right:
            value: {}
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.GcpInstance
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.GcpZone
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.GcpNetwork
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.RemotePort
            iscontext: true
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.RemoteProtocol
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: 848c9e33-315c-435c-8104-cd1eeba70f45
    type: title
    task:
      id: 848c9e33-315c-435c-8104-cd1eeba70f45
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 350,
          "y": 2345
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "16":
    id: "16"
    taskid: 1f3cf208-77b3-4820-80e1-951a50ec342f
    type: condition
    task:
      id: 1f3cf208-77b3-4820-80e1-951a50ec342f
      version: -1
      name: Does the remediation allow rule exist?
      description: Check whether the last command returned remediation allow rule or not.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "23"
      "yes":
      - "18"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: GoogleCloudCompute.Firewalls
                accessor: name
            iscontext: true
          right:
            value: {}
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 860
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "18":
    id: "18"
    taskid: c3660121-04fb-4300-8fe3-e11064217f81
    type: regular
    task:
      id: c3660121-04fb-4300-8fe3-e11064217f81
      version: -1
      name: Get network tags information.
      description: Returns the tags of instance.
      script: Google Cloud Compute|||gcp-compute-get-instance
      type: regular
      iscommand: true
      brand: Google Cloud Compute
    nexttasks:
      '#none#':
      - "27"
    scriptarguments:
      instance:
        complex:
          root: inputs.GcpInstance
      zone:
        complex:
          root: inputs.GcpZone
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1720
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "23":
    id: "23"
    taskid: 7a35769a-dcee-42e0-82dd-89cd990c4aab
    type: title
    task:
      id: 7a35769a-dcee-42e0-82dd-89cd990c4aab
      version: -1
      name: Create allow and block rules
      type: title
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "25"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1110
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "24":
    id: "24"
    taskid: d58efdff-2746-431e-8010-f9168b5efb22
    type: regular
    task:
      id: d58efdff-2746-431e-8010-f9168b5efb22
      version: -1
      name: Add block everything firewall rule
      description: Creates a firewall rule in the specified project using the data included in the request.
      script: Google Cloud Compute|||gcp-compute-insert-firewall
      type: regular
      iscommand: true
      brand: Google Cloud Compute
    nexttasks:
      '#none#':
      - "18"
    scriptarguments:
      denied:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: ',ports='
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: inputs.RemoteProtocol
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: ipprotocol=
              suffix: {}
      direction:
        simple: INGRESS
      name:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: remediation-block-port-
              suffix:
                value:
                  simple: '-'
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: inputs.RemoteProtocol
                iscontext: true
      network:
        complex:
          root: inputs.GcpNetwork
      priority:
        simple: "1"
      sourceRanges:
        simple: 0.0.0.0/0
      targetTags:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: remediation-tag-
              suffix: {}
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: '-'
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: inputs.RemoteProtocol
                iscontext: true
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1500
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "25":
    id: "25"
    taskid: 5a5a01bf-4ada-4624-8215-0dedefc853c2
    type: regular
    task:
      id: 5a5a01bf-4ada-4624-8215-0dedefc853c2
      version: -1
      name: Add allow rule
      description: Creates a firewall rule in the specified project using the data included in the request.
      script: Google Cloud Compute|||gcp-compute-insert-firewall
      type: regular
      iscommand: true
      brand: Google Cloud Compute
    nexttasks:
      '#none#':
      - "24"
    scriptarguments:
      allowed:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: ',ports='
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: inputs.RemoteProtocol
                iscontext: true
              suffix: {}
          - operator: concat
            args:
              prefix:
                value:
                  simple: ipprotocol=
              suffix: {}
      direction:
        simple: INGRESS
      name:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: remediation-allow-port-
              suffix:
                value:
                  simple: '-'
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: inputs.RemoteProtocol
                iscontext: true
      network:
        complex:
          root: inputs.GcpNetwork
      priority:
        simple: "0"
      sourceRanges:
        simple: 172.16.0.0/12,10.0.0.0/8,192.168.0.0/16
      targetTags:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: remediation-tag-
              suffix: {}
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: '-'
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: inputs.RemoteProtocol
                iscontext: true
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 900,
          "y": 1290
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "27":
    id: "27"
    taskid: 7413070c-c8d2-435f-8aae-3225cae3e03d
    type: condition
    task:
      id: 7413070c-c8d2-435f-8aae-3225cae3e03d
      version: -1
      name: Does the network tags already exist on the instance?
      description: |+
        Check whether the last command returned remediation tag or not. If the tag is not present, the tag remediation-tag-{port#}-{protocol} is created.

      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "30"
      "yes":
      - "2"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              complex:
                root: GoogleCloudCompute.Instances.tags
                accessor: items
            iscontext: true
          right:
            value:
              complex:
                root: inputs.RemotePort
                transformers:
                - operator: concat
                  args:
                    prefix:
                      value:
                        simple: remediation-tag-
                    suffix: {}
                - operator: concat
                  args:
                    prefix: {}
                    suffix:
                      value:
                        simple: '-'
                - operator: concat
                  args:
                    prefix: {}
                    suffix:
                      value:
                        simple: inputs.RemoteProtocol
                      iscontext: true
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 1980
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "30":
    id: "30"
    taskid: 3e5be817-d180-46ba-8d10-5e399abad5e6
    type: regular
    task:
      id: 3e5be817-d180-46ba-8d10-5e399abad5e6
      version: -1
      name: Add and set network tags
      description: Add network tag for the specified instance.
      script: Google Cloud Compute|||gcp-compute-add-network-tag
      type: regular
      iscommand: true
      brand: Google Cloud Compute
    nexttasks:
      '#none#':
      - "2"
    scriptarguments:
      instance:
        complex:
          root: inputs.GcpInstance
      tag:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: remediation-tag-
              suffix: {}
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: '-'
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: inputs.RemoteProtocol
                iscontext: true
      zone:
        complex:
          root: inputs.GcpZone
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 740,
          "y": 2170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "32":
    id: "32"
    taskid: 6822b4bb-5d01-48c2-8aca-13693dbb031a
    type: regular
    task:
      id: 6822b4bb-5d01-48c2-8aca-13693dbb031a
      version: -1
      name: Lookup Firewall rule names with associated network
      description: Retrieves the list of firewall rules available to the specified project. If these don't exist, the allow and block rules are created of the format remediation-[allow|block]-port-{port#}-{protocol}.
      script: Google Cloud Compute|||gcp-compute-list-firewall
      type: regular
      iscommand: true
      brand: Google Cloud Compute
    nexttasks:
      '#none#':
      - "16"
    scriptarguments:
      filters:
        complex:
          root: inputs.RemotePort
          transformers:
          - operator: concat
            args:
              prefix:
                value:
                  simple: name="remediation-allow-port-
              suffix:
                value:
                  simple: '-'
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: inputs.RemoteProtocol
                iscontext: true
          - operator: concat
            args:
              prefix: {}
              suffix:
                value:
                  simple: '"'
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 605
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 2360,
        "width": 930,
        "x": 350,
        "y": 50
      }
    }
  }
inputs:
- key: GcpInstance
  value: {}
  required: true
  description: The name of the GCP instance that has the public ip.
  playbookInputQuery:
- key: GcpZone
  value: {}
  required: true
  description: The zone of the GCP instance that is hosted in.
  playbookInputQuery:
- key: GcpNetwork
  value: {}
  required: true
  description: The VPC network of the GCP instance.
  playbookInputQuery:
- key: RemotePort
  value:
    complex:
      root: alert
      accessor: remoteport
  required: true
  description: The remote port that is publicly exposed to.
  playbookInputQuery:
- key: RemoteProtocol
  value: {}
  required: true
  description: The remote protocol that is publicly exposed to.
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.5.0
