id: AWS - Unclaimed S3 Bucket Remediation
version: -1
name: AWS - Unclaimed S3 Bucket Remediation
description: The playbook will create the unclaimed S3 bucket.
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: 9fe5d2f0-2790-439f-8efc-9769afc163c8
    type: start
    task:
      id: 9fe5d2f0-2790-439f-8efc-9769afc163c8
      version: -1
      name: ""
      iscommand: false
      brand: ""
      description: ''
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "1":
    id: "1"
    taskid: 4f2dc246-1b92-4458-872a-f9de26289bb2
    type: condition
    task:
      id: 4f2dc246-1b92-4458-872a-f9de26289bb2
      version: -1
      name: Is AWS S3 enabled and is Input value defined?
      description: Determines if theAWS integration instance is configured and Input values are defined.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "4"
      "yes":
      - "5"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isExists
          left:
            value:
              complex:
                root: modules
                filters:
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.brand
                      iscontext: true
                    right:
                      value:
                        simple: AWS - S3
                - - operator: isEqualString
                    left:
                      value:
                        simple: modules.state
                      iscontext: true
                    right:
                      value:
                        simple: active
            iscontext: true
          right:
            value: {}
      - - operator: isExists
          left:
            value:
              complex:
                root: inputs.BucketName
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 190
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "2":
    id: "2"
    taskid: db3aa7fa-2f64-48a8-8d8b-788168bdbfd2
    type: regular
    task:
      id: db3aa7fa-2f64-48a8-8d8b-788168bdbfd2
      version: -1
      name: Create S3 Bucket
      description: Create AWS S3 bucket.
      script: AWS - S3|||aws-s3-create-bucket
      type: regular
      iscommand: true
      brand: AWS - S3
    nexttasks:
      '#none#':
      - "4"
    scriptarguments:
      bucket:
        complex:
          root: inputs.BucketName
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 955
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "4":
    id: "4"
    taskid: 2c690e57-90d8-4c62-8ef4-6a3987672f52
    type: title
    task:
      id: 2c690e57-90d8-4c62-8ef4-6a3987672f52
      version: -1
      name: Done
      type: title
      iscommand: false
      brand: ""
      description: ''
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 440,
          "y": 1170
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "5":
    id: "5"
    taskid: 4f0282e5-cc9a-4c12-847e-8274ebcf9480
    type: regular
    task:
      id: 4f0282e5-cc9a-4c12-847e-8274ebcf9480
      version: -1
      name: List all S3 buckets
      description: List all S3 buckets in AWS account
      script: AWS - S3|||aws-s3-list-buckets
      type: regular
      iscommand: true
      brand: AWS - S3
    nexttasks:
      '#none#':
      - "7"
    separatecontext: false
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 440
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
  "7":
    id: "7"
    taskid: 456756de-40f0-48b6-85e2-2b07c1b459f5
    type: condition
    task:
      id: 456756de-40f0-48b6-85e2-2b07c1b459f5
      version: -1
      name: Does the unclaimed S3 bucket already exists?
      description: Checks if the unclaimed s3 bucket already exists.
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      '#default#':
      - "2"
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: inList
          left:
            value:
              complex:
                root: AWS.S3.Buckets
                accessor: BucketName
            iscontext: true
          right:
            value:
              complex:
                root: inputs.BucketName
            iscontext: true
    continueonerrortype: ""
    view: |-
      {
        "position": {
          "x": 450,
          "y": 680
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
    skipunavailable: false
    quietmode: 0
    isoversize: false
    isautoswitchedtoquietmode: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1185,
        "width": 390,
        "x": 440,
        "y": 50
      }
    }
  }
inputs:
- key: BucketName
  value: {}
  required: true
  description: Unclaimed S3 bucket name.
  playbookInputQuery:
outputs: []
tests:
- No tests (auto formatted)
fromversion: 6.5.0
